import { WorkoutTemplate } from '../types/index.js';

export const defaultWorkoutTemplates: WorkoutTemplate[] = [
  {
    id: 'ABC-A',
    name: 'Trening A - Klatka + Barki',
    description: 'Klasyczny trening klatki piersiowej i barków z wysoką objętością. Idealny dla hipertrofii. ~90 min.',
    category: 'strength',
    estimatedDuration: 90,
    difficulty: 'intermediate',
    color: 'bg-red-600',
    icon: '💪',
    exercises: [
      'Rozgrzewka: Wioślarz 1000m (opór 7/8)',
      'Rozgrzewka: Ski-erg 1000m (opór 7/8)',
      'Wyciskanie Hummer wąsko – 5x (12/10/10/8/8)',
      'Wyciskanie Smith dodatnia 15° – 5x (12/10/10/8/8)',
      'Wyciskanie hantli pozioma – 5x12-15',
      'Wznosy sztangi wzdłuż tułowia – 5x (12/10/10/8/8)',
      'Wznosy hantli na boki siedząc – 5x12-15',
      'A\'lahy wyciąg górny – 4x MAX',
      'Finisher: Rower 300 Cal (opór 6/7)',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ABC-B',
    name: 'Trening B - Plecy + Barki Tylne',
    description: 'Trening pleców z akcentem na szerokość i grubość. Core i barki tylne. ~90 min.',
    category: 'strength',
    estimatedDuration: 90,
    difficulty: 'intermediate',
    color: 'bg-blue-600',
    icon: '🏋️',
    exercises: [
      'Rozgrzewka: Wioślarz 1000m (opór 7/8)',
      'Rozgrzewka: Ski-erg 1000m (opór 7/8)',
      'Hummer z góry szeroko – 5x (12/10/10/8/8)',
      'Hummer wiosło podchwytem – 5x (12/10/10/8/8)',
      'Ściąganie łapek poziomo – 5x (12/10/10/8/8)',
      'Prostownik – 3x MAX',
      'Wyciskanie żołnierskie siedząc – 5x12-15',
      'Odwrotny butterfly – 5x12-15',
      'Podciąganie kolan na stojaku – 4x MAX',
      'Finisher: Rower 300 Cal (opór 6/7)',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ABC-C',
    name: 'Trening C - Nogi + Ramiona',
    description: 'Dzień nóg z supersetami na biceps i triceps. Kompleksowy trening dolnej partii. ~90 min.',
    category: 'strength',
    estimatedDuration: 90,
    difficulty: 'intermediate',
    color: 'bg-green-600',
    icon: '🦵',
    exercises: [
      'Rozgrzewka: Wioślarz 1000m (opór 7/8)',
      'Rozgrzewka: Ski-erg 1000m (opór 7/8)',
      'Wykroki – 5x20 wykroków',
      'Przysiad kettla z przodu – 5x12-15 (12kg)',
      'Wypychanie suwnicy – 4x (12/10/10/8)',
      'Zginanie podudzia (1 noga) – 5x12-15',
      'SUPERSET: Biceps młotek – 4x12-15',
      'SUPERSET: Triceps francuskie – 4x12-15',
      'SUPERSET: Biceps dolny wyciąg – 4x12-15',
      'SUPERSET: Triceps górny wyciąg – 4x12-15',
      'Finisher: Rower 300 Cal (opór 6/7)',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'Push/Pull-PUSH',
    name: 'PUSH - Klatka + Barki + Nogi',
    description: 'Nowoczesny push day łączący górę i nogi. Trening pchający z solidną objętością. ~75 min.',
    category: 'strength',
    estimatedDuration: 75,
    difficulty: 'intermediate',
    color: 'bg-orange-600',
    icon: '🔥',
    exercises: [
      '1. Przysiad Hack maszyna – 5x (12/10/10/8/8)',
      '2. Wyciskanie Hummer pozioma – 5x (12/10/10/8/8)',
      '3. Wyciskanie hantli nad głowę – 5x (12/10/10/8/8)',
      '4. Przysiad bułgarski – 3x8-10 (na nogę)',
      '5. Wspięcia na palce – 3x12-15',
      '6. Wznosy bokiem hantli – 3x12-15',
      '7. Wyciskanie hantli dodatnia – 5x (12/10/10/8/8)',
      '8. Rozpiętki butterfly – 3x12-15',
      'Finisher: Plank – 2x MAX (1 min przerwy)',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'Push/Pull-PULL',
    name: 'PULL - Plecy + Nogi Tylne',
    description: 'Pull day z akcentem na plecy i dwugłowe uda. Funkcjonalny i efektywny. ~75 min.',
    category: 'strength',
    estimatedDuration: 75,
    difficulty: 'intermediate',
    color: 'bg-purple-600',
    icon: '💎',
    exercises: [
      '1. Martwy ciąg z haków – 5x (12/10/10/8/8)',
      '2. Ściąganie szeroki podchwyt – 5x (12/10/10/8/8)',
      '3. Wiosłowanie kettlem – 4x10-12',
      '4. Ściąganie V-bloczek – 5x (12/10/10/8/8)',
      '5. Uginanie nóg leżąc – 3x12-15',
      '6. Hip Thrust – 3x8-10',
      '7. Face Pulls – 3x12-15',
      '8. Uginanie ramion ze sztangą prostą – 3x10-12',
      '9.Uginanie ramion hantlami (naprzemiennie) – 3x12-15',
      'Finisher: AirBike 30 Cal',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'Push/Pull-CONDITIONING',
    name: 'CONDITIONING - Funkcjonalność',
    description: 'Dzień kondycyjny i funkcjonalny. Interwały, AMRAP i praca sankami. ~60 min.',
    category: 'cardio',
    estimatedDuration: 60,
    difficulty: 'advanced',
    color: 'bg-yellow-500',
    icon: '⚡',
    exercises: [
      '4 RUNDY: Rower 10 Cal',
      '4 RUNDY: Ski-erg 250m',
      'AMRAP 15min: Sit-up x15',
      'AMRAP 15min: Martwy ciąg kettla x15',
      'AMRAP 15min: Wioślarz 500m',
      '3 RUNDY: Pchanie sanek 20m (40kg)',
      '3 RUNDY: Przyciąganie sanek 20m (40kg)',
      '3 RUNDY: Wyciskanie klatka 14x2/x10',
      '3 RUNDY: Wykroki worek 10kg 20m',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
];

export const swimmingTemplates = [
  {
    id: 'basen_30',
    name: 'BASEN 30 MIN',
    description: 'Krótki trening pływacki - regeneracja aktywna',
    category: 'cardio' as const,
    estimatedDuration: 30,
    difficulty: 'beginner' as const,
    color: 'bg-cyan-600',
    icon: '🏊',
    exercises: [
      '🏁 ROZGRZEWKA (5 min)',
      '• 200m dowolny styl spokojnie',
      '• 4x25m z przerwą 15s (każdy styl inny)',
      '',
      '🔥 CZĘŚĆ GŁÓWNA (20 min)',
      '• 4x100m kraul (przerwa 30s) - tempo umiarkowane',
      '• 4x50m grzbiet (przerwa 20s)',
      '• 2x100m kraul z pull-buoy (tylko ręce)',
      '• 4x25m sprint kraul (przerwa 20s)',
      '',
      '❄️ WYCISZENIE (5 min)',
      '• 200m dowolny styl bardzo spokojnie',
      '• Stretching w wodzie - 2 min',
      '',
      '📊 ŁĄCZNIE: ~1000m'
    ]
  },
  {
    id: 'basen_45',
    name: 'BASEN 45 MIN',
    description: 'Średni trening - wytrzymałość + technika',
    category: 'cardio' as const,
    estimatedDuration: 45,
    difficulty: 'intermediate' as const,
    color: 'bg-blue-600',
    icon: '🏊‍♂️',
    exercises: [
      '🏁 ROZGRZEWKA (8 min)',
      '• 300m dowolny styl spokojnie',
      '• 4x50m mix stylów (kraul/grzbiet/żabka/motyl)',
      '• 4x25m drile techniczn (przerwa 15s)',
      '',
      '🔥 CZĘŚĆ GŁÓWNA - BLOK 1: Wytrzymałość (15 min)',
      '• 5x200m kraul (przerwa 45s) - tempo 70-80%',
      '• Cel: utrzymanie równego czasu na każdym odcinku',
      '',
      '💪 CZĘŚĆ GŁÓWNA - BLOK 2: Szybkość (12 min)',
      '• 8x50m kraul sprint (przerwa 30s)',
      '• 4x100m z pull-buoy tempo 80% (przerwa 30s)',
      '• 4x25m sprint maksymalny (przerwa 30s)',
      '',
      '🎯 CZĘŚĆ GŁÓWNA - BLOK 3: Technika (5 min)',
      '• 4x50m dowolny styl - koncentracja na technice',
      '• 2x50m tylko nogi z deską',
      '',
      '❄️ WYCISZENIE (5 min)',
      '• 300m dowolny styl bardzo spokojnie',
      '• Stretching w wodzie - 2 min',
      '',
      '📊 ŁĄCZNIE: ~2000m'
    ]
  }
];