import { WorkoutTemplate } from '../types/index.js';

export const defaultWorkoutTemplates: WorkoutTemplate[] = [
  {
    id: 'default-1',
    name: 'Full Body Starter',
    description: 'Trening ogólnorozwojowy dla początkujących. Obejmuje całe ciało w jednym planie.',
    category: 'strength',
    estimatedDuration: 45,
    difficulty: 'beginner',
    color: 'bg-green-600',
    icon: '💪',
    exercises: [
      'Przysiad z masą ciała – 3x12',
      'Pompki – 3x10',
      'Plank – 3x30s',
      'Wykroki – 3x12 (na nogę)',
      'Wiosłowanie hantlem – 3x10',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'default-2',
    name: 'Cardio Express',
    description: 'Szybki trening cardio bez sprzętu, idealny do spalania kalorii.',
    category: 'cardio',
    estimatedDuration: 30,
    difficulty: 'intermediate',
    color: 'bg-red-600',
    icon: '🏃‍♂️',
    exercises: [
      'Bieg w miejscu – 1 min',
      'Burpees – 3x12',
      'Mountain Climbers – 3x20',
      'Jumping Jacks – 3x30',
      'Plank – 3x45s',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'default-3',
    name: 'Push & Pull Split',
    description: 'Dwudniowy plan skupiający się na treningu góry ciała.',
    category: 'strength',
    estimatedDuration: 60,
    difficulty: 'intermediate',
    color: 'bg-indigo-600',
    icon: '🏋️‍♀️',
    exercises: [
      'Wyciskanie sztangi leżąc – 4x8',
      'Podciąganie – 4x max',
      'Wyciskanie hantli nad głowę – 3x10',
      'Wiosłowanie sztangą – 3x10',
      'Uginanie ramion z hantlami – 3x12',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'default-4',
    name: 'Mobility Flow',
    description: 'Zestaw ćwiczeń poprawiających mobilność i elastyczność.',
    category: 'custom',
    estimatedDuration: 25,
    difficulty: 'beginner',
    color: 'bg-yellow-500',
    icon: '🧘‍♀️',
    exercises: [
      'Cat-Cow – 2 min',
      'Child’s Pose – 1 min',
      'Shoulder Circles – 3x20',
      'Leg Swings – 3x15 (na nogę)',
      'Neck Rolls – 3x10',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'default-5',
    name: 'HIIT 15',
    description: 'Bardzo intensywny trening interwałowy — 15 minut mocnego spalania!',
    category: 'cardio',
    estimatedDuration: 15,
    difficulty: 'advanced',
    color: 'bg-orange-600',
    icon: '🔥',
    exercises: [
      'Sprint w miejscu – 30s',
      'Burpees – 20s',
      'Przysiady z wyskokiem – 20s',
      'Mountain Climbers – 20s',
      'Odpoczynek – 30s',
      'Powtórz 4 rundy',
    ],
    isCustom: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
];
